//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCGrab.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.Image_Store = new HashSet<Image_Store>();
            this.Order = new HashSet<Order>();
        }
    
        public int id { get; set; }
        public string store_id { get; set; }
        public string user_id { get; set; }
        public string store_name { get; set; }
        public string store_description { get; set; }
        public string store_address { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string operating_hours { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual ICollection<Image_Store> Image_Store { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}
