//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCGrab.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Accounts
    {
        public int id { get; set; }
        public string user_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public Nullable<int> role_id { get; set; }
        public Nullable<int> status { get; set; }
        public string verify_code { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        public virtual User_Accounts User_Accounts1 { get; set; }
        public virtual User_Accounts User_Accounts2 { get; set; }
        public virtual User_Role User_Role { get; set; }
    }
}
