//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCGrab.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Information
    {
        public User_Information()
        {
            this.Image = new HashSet<Image>();
        }
    
        public int id { get; set; }
        public string user_id { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> store_id { get; set; }
    
        public virtual ICollection<Image> Image { get; set; }
    }
}
