//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCGrab.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Role
    {
        public User_Role()
        {
            this.User_Accounts = new HashSet<User_Accounts>();
        }
    
        public int role_id { get; set; }
        public string rolename { get; set; }
    
        public virtual ICollection<User_Accounts> User_Accounts { get; set; }
        public virtual User_Role User_Role1 { get; set; }
        public virtual User_Role User_Role2 { get; set; }
        public virtual User_Role User_Role11 { get; set; }
        public virtual User_Role User_Role3 { get; set; }
    }
}
